### ISSUE TITLE
Include an explicit licence for umake

### ISSUE THREAD

**Issue by kalebo** [grisha85/umake#13]
Consider licensing umake under an opensource license.

Thus quoth the github documentation:
> ... Without a license, the default copyright laws apply, meaning that you retain all rights to your source code and no one may reproduce, distribute, or create derivative works from your work. If you're creating an open source project, we strongly encourage you to include an open source license. 

Further it would be ideal of the relationship between umake and [drivenets](drivenets.com) was made explicit as well. E.g., should the community expect to see further development of umake by drivenets?

**Comment by grisha85** [comment]
Added license. Drivenets not stand behind the project it's initiative of it's workers
