### ISSUE TITLE
Local build not working on clean Ubuntu 18.04

### ISSUE THREAD

**Issue by oshamash** [grisha85/umake#21]
python-graph installation always fail.

Optional solution: run 
`sudo apt install build-essential python-dev libxml2 libxml2-dev zlib1g-dev`

Also missing somewhere explicitly saying that `umake` is a python3 only library,
Installing via pip-install will cause this to not work (use `pip3 install` when having dual python)

Consider either doing this as part of install routine, or add it to README

**Comment by grisha85** [comment]
done
